### ISSUE TITLE
todo list tmap4

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#599]
- [x] Add horizontal legends
- [x] Improve auto-placement of legends using horizontal legends 
- [x] Add other standard layers functions (`tm_lines` and `tm_text`)
- [x] Improve color palette options #566
- [x] Improve inset legend placement
- [x] Add `view` mode plotting functions
- [x] Add `tm_basemap` (probably using `maptiles`)
- [x] Approach `stars` cubes: select individual dimension values as variables and the set attributes as one variable #597
- [x] Migrate `tm_symbols` symbol options (icons, grobs, pngs, etc) from tmap3
- [x] Add `tm_grid` and `tm_graticules`
- [x] Migrate map elements (`tm_compass`, `tm_scale_bar`, and `tm_credits`)
- [ ] Think about how to add inset maps (and start GH issue to ask people)
- [x] ~~Add simplification for vector shapes~~ (dropped)
- [x] Calculate number of facets in step1, in order to now the downscale size of rasters
- [x] Create an example external package (to test extendibility) #565
- [x] Redirect tmap3 code to make it backwards compatible (and check if everything is covered in tmap4) #861 
- [x] How to add additional charts, e.g. histograms? #581
- [x] `view`: Think about multiple zoom levels: apply scale functions to multiple aggregation levels?
- [x] `view`: Add/Implement non-standard legends
- [x] `view`: Think about interaction (e.g. shiny functions): migrate current functions? 
- [ ] `view`: Popups: what should/could be included? Also mini charts?
- [x] `view`: See what recent leaflet add-ons could be used (e.g. `leafgl`)
- [x] Update `tmap_save`
- [x] Update `tmap_arrange`
- [x] Add main titles
- [x] How to re implement option `earth.boundary`
- [x] `view`: Possible/easy yet to use a different crs (rasters were not possible in the past)?
- [ ] Improve running time (ongoing task)
- [x] Improve code documentation (ongoing task)
- [x] Add documentation
- [x] Add examples
- [x] Think about other modes: e.g. `rayshare`? `ggplot` (for fun) `celium`?
- [x] `plot` add globe view #457 #564
- [x] Add global color options (e.g. saturation used in style classic)
- [x] Add global scaling argument
- [x] Re-implement text functions (`along.line`, `auto.placement`, `remove.overlap`)
- [x] `tmaptools` still needed for `tmap`?
- [x] Add optional arguments `...` to pass arguments to transformation functions (e.g. cartogram)
- [x] Check other dependencies
- [x] How/where to determine plotting order of features?
- [x] Write vignettes
- [x] Update book https://github.com/r-tmap/tmap-book/pull/22
- [x] Check #607
